var chistes = [
        
        "La mayor exportación de Australia son los boomerangs. También son la mayor importación",
        "Intenté organizar un torneo profesional de escondite, pero fue un completo fracaso. Los buenos jugadores son difíciles de encontrar.",
        "Hay tres tipos de personas en el mundo: los que saben contar y los que no.",
        "El otro día vendí mi aspiradora. Lo único que hacía era acumular polvo.",
        "¿Qué le dice un jardinero a otro? Nos vemos cuando podamos.",
        "¿Cómo se llama el hermano vegetariano de Bruce Lee? Broco Lee.",
        "Me gustan los elefantes. Todo lo demás me parece irrelefante.",
        "Me gustan los elefantes. Todo lo demás me parece irrelefante.",
        "¿Qué hay peor que encontrarse un gusano en una manzana? Encontrarse medio.",
        "¿De dónde sale la porcelana? De las porceovejas.",
        "¿Cómo se llama un boomerang que no vuelve? Palo.",
        "Tengo un amigo otaku que estaba triste, así que lo animé.        ",
        "¿Has oído hablar del astronauta claustrofóbico? Solo necesitaba un poco de espacio.",
        "¿Por qué no pueden hablar los dinosaurios? Porque están muertos.",
        "¿Qué le dice un 2 a un 0? Veinte conmigo, guapetón.        ",
        "Mi nuevo diccionario es malísimo. No solo eso, también es malísimo.        ",
        "¿Cuál es el animal más tonto de la selva? El oso polar.        ",
        "Ayer fui al McDonald's con cuatro amigos. Tres eran de sagitario. Y el cuarto de libra.",
        "¿Cuál es el café más peligroso del mundo? El ex-preso        ",
        "¿Para qué va una caja al gimnasio? Para hacerse caja fuerte.        ",
        "¿Cómo se despiden los químicos? Ácido un placer.        ",
        "¿Qué le dice una iguana a otra? Somos iguanitas.        ",
        "¿Qué hace una abeja en un gimnasio? Zumba.        ",
        "¿Cómo se llama el campeón de buceo japonés? Tokofondo.",
        "Se abre el telón y se ve un tetrabrik de Don Simón. ¿Cómo se llama la película? Es tinto básico.",
        "¿Qué le dice un ganso a una gansa? ¡Vengansa!        ",
        "Si se muere una pulga, ¿dónde va? Al pulgatorio",
        "- ¿Qué es un pez en un cine? - Un mero espectador",
        "¿Por qué la gallina cuida tanto a sus pollitos? Porque le costó un huevo tenerlos",
        "- Iba a contar un chiste sobre sodio... pero Na.",
        "¿Qué le dice una impresora a otra? ¿Esa hoja es tuya o es impresión mía?.",
        "¿Cómo se dice puerta en inglés? Door. ¿Y el que las vende? Vendedoor. ¿Y el que las compra? Compradoor.",
        "¿Dónde vive Iron Man? Iron Know.        ",
        "Los hippies no orinan: hacen peace.",
        "¿Qué hace una vaca con los ojos cerrados? Leche concentrada.",
        "¿De dónde vienen los hámster? De Hamsterdam.",
        "¿Qué le dice una gallina deprimida a otra gallina deprimida? Necesitamos apoyo.",
        "Papá, papá, ¿puedo ir al cine? Sí, pero no entres.",
        "Doctor, doctor, tengo paperas. Pues toma 2? y ya tienes pá plátanos.",
        "¿Qué hace un vampiro conduciendo un tractor? Sembrar el miedo.       ",
        "¿Cuál es el colmo del atún? Que le den la lata.",
        "¿Qué le dice un árbol a otro? ¡Qué pasa tronco!        ",
        "¿Por qué se suicidó el libro de matemáticas? Porque tenía muchos problemas.",
        "¿Por qué los diabéticos no pueden vengarse? Porque la venganza es dulce.",
        "¿Por qué los patos no tienen amigos? Porque son muy antipáticos",
        "Hola, ¿está Agustín? No, estoy incomodín.",
        "¿Qué le dice una barra de pan a otra? Te presento a una miga.",
        "Una familia ocupó un terreno en Hawaii. Ahora a ver quién la desaloha.",
        "¿Por qué los del Lepe no salen de la comunidad? Porque hay un cartel que pone Huelva.",
        "Hola muñeca. Hola tobillo.",
        "Qué es un pelo en una cama? El bello durmiente.",
        "¿Qué le dice un huevo a una sartén? Me tienes frito.        ",
        "Están dos borrachos y uno le dice al otro: ?No sigas bebiendo que te estás poniendo borroso?.",
        "Si los ciempiés tienen 100 pies... ¿entonces los piojos tienen 3,14 ojos?",
        "¿Por qué la gallina cuida tanto a sus pollitos? Porque le costó un huevo tenerlos.",
        "¿Qué le dice el 3 al 30? Para ser como yo debes ser sincero.",
        "¿Cuál es el superhéroe de los perros? El dóberman.",
        "Si los zombis llegan a la tercera edad... ¿zombiejitos?",
        "¿Por qué la luna es más grande que el sol? Porque la dejan salir de noche.",
        "¿Cuál es el colmo de un puerco espín? Que le dé mala espina.",
        "Van 2 videntes en una moto y se cae el del médium.",
        "¿Qué le dice un semáforo en amarillo a los coches? No me miren, que me estoy cambiando.",
        "¿Por qué los programadores prefieren el invierno? Porque el verano tiene demasiados errores",
        "¿Por qué los astronautas no pueden tomar refrescos? Porque las burbujas son impracticables en gravedad cero",
        "¿Por qué la guitarra eléctrica era tan triste? Porque tenía demasiados bajos",
        "¿Por qué las bibliotecas son los lugares más ruidosos? Porque los libros tienen muchas historias que contar",
        "¿Por qué el helado no puede mantener un secreto? Porque siempre se derrite",
        "¿Por qué los panaderos siempre están cansados? Porque amasan todo el día",
        "¿Por qué los perros no pueden bailar? Porque tienen dos patas izquierdas",
        "¿Por qué los pájaros se van al sur en invierno? Porque es demasiado lejos para caminar",
        "¿Por qué los peces no son buenos músicos? Porque siempre tocan en escala",
        "¿Por qué los músicos siempre tienen frío? Porque siempre están en clave menor",
        "¿Por qué el reloj hace tic-tac? Porque si hiciera toc-tic nadie llegaría a tiempo",
        "¿Por qué el mar siempre suena bien? Porque tiene muchas olas",
        "¿Por qué los ojos no pueden ser amigos? Porque se ven de vez en cuando",
        "¿Por qué los bomberos siempre están fríos? Porque tienen muchas mangueras",
        "¿Por qué los pájaros no usan teléfonos? Porque ya tienen sus propias líneas aéreas",
        "¿Por qué las vacas usan relojes? Para saber la hora de la leche",
        "¿Por qué los robots siempre pierden en el póker? Porque tienen una mala expresión facial",
        "¿Por qué los médicos son los peores pacientes? Porque siempre piensan que tienen derecho a una segunda opinión",
        "¿Por qué los magos son tan buenos en matemáticas? Porque siempre saben cómo hacer desaparecer un problema",
        "¿Por qué los futbolistas no hacen una fiesta en la selva? Porque siempre hay un león que les come la carne",
        "¿Por qué los programadores siempre confunden Halloween con Navidad? Porque Oct 31 es igual a Dec 25",
        "¿Por qué los buitres no usan Facebook? Porque ya son expertos en encontrar cosas muertas",
        "¿Por qué las computadoras van al médico? Porque tienen virus",
        "¿Por qué las gaviotas viven cerca del mar? Porque si vivieran lejos serían bolsas de basura",
        "¿Por qué los niños de la selva no juegan al fútbol? Porque no hay arcos",
        "¿Por qué los koalas no son osos? Porque no cumplen con los requisitos de las Koalificaciones",
        "¿Por qué los abogados no pueden llevar a su perro al trabajo? Porque siempre ladran objeciones",
        "¿Por qué los esqueletos son siempre tan calmados? Porque nada los hace temblar",
        "¿Por qué los dinosaurios no pueden hablar? Porque están extintos",
        "¿Por qué los carpinteros no tienen muchos amigos? Porque siempre están clavando algo",
        "¿Por qué las nubes no salen en las fotos? Porque siempre se ponen detrás del flash",
"¿Por qué los árboles prefieren tener wifi en lugar de celular? Porque siempre pierden la señal",
"¿Por qué los músicos no pueden hacer una buena taza de café? Porque siempre quieren darle un solo",
"¿Por qué las gallinas siempre miran hacia arriba? Porque tienen miedo de que les caiga el cielo",
"¿Por qué los cerdos no pueden cantar bien? Porque siempre se les escapa un oink",
"¿Por qué los astronautas nunca hacen fiestas en el espacio? Porque no hay ambiente",
"¿Por qué los leones siempre son los reyes de la selva? Porque los elefantes no quieren el trabajo",
"¿Por qué los barcos siempre son tan amables? Porque tienen muchos muelles",
"¿Por qué los escarabajos son tan buenos para el fútbol? Porque tienen muchas patas",
"¿Por qué los médicos siempre están cansados? Porque trabajan en el turno de noche",
"¿Por qué los perros no pueden hacer pizzas? Porque siempre se comen los ingredientes",
"¿Por qué los monos nunca son buenos detectives? Porque siempre se cuelgan de la pista",
"¿Por qué los pájaros nunca se enferman? Porque tienen una buena ala-ta inmunidad",
"¿Por qué los barberos son tan buenos en la bolsa de valores? Porque siempre tienen una buena tijera para recortar pérdidas",
"¿Por qué las vacas siempre están deprimidas? Porque siempre ven la vida en blanco y negro",
"¿Por qué las jirafas nunca juegan baloncesto? Porque siempre tienen la cabeza en las nubes",
"¿Por qué los caballos no pueden tomar café? Porque siempre lo beben demasiado caliente y se les queda la crin parada",
"¿Por qué los cocineros son tan buenos en el piano? Porque siempre saben cuándo darle la vuelta a la tortilla",
"¿Por qué los elefantes no pueden jugar al escondite? Porque siempre tienen problemas para esconder su trompa",
"¿Por qué los gatos nunca se hacen amigos de los ratones? Porque siempre les tienen envidia de su queso",
"¿Por qué los futbolistas nunca juegan en la lluvia? Porque siempre se mojan demasiado",
"¿Por qué los espejos siempre tienen buena memoria? Porque nunca olvidan una cara",
"¿Por qué los payasos siempre son tan alegres? Porque siempre tienen un as bajo la manga",
"¿Por qué los pececitos nunca van a la escuela? Porque siempre están en el agua",
"¿Por qué los jugadores de ajedrez siempre son tan silenciosos? Porque siempre piensan antes de mover",
"¿Por qué las ranas nunca hacen una buena barbacoa? Porque siempre quieren saltar el fuego",
"¿Por qué las pelotas siempre tienen miedo de salir del campo? Porque no quieren perder la cancha",
"¿Por qué las aves siempre cantan tan temprano en la mañana? Porque quieren ser los primeros en dar la nota",
"¿Por qué los caballos nunca aprenden a leer? Porque siempre están ocupados galopando",
"¿Por qué los perros no pueden ser bomberos? Porque siempre se distraen con las mangueras",
"¿Por qué los delfines nunca hacen un buen negocio? Porque siempre pierden el marco de la situación",
"¿Por qué los monos nunca pueden ser astronautas? Porque no pueden pagar la tarifa del plátano espacial",
"¿Por qué los lagartos siempre tienen frío? Porque no pueden encontrar su abrigartija",
"¿Por qué los koalas nunca salen de casa? Porque siempre se quedan dormidos en la puerta",
"¿Por qué los castores siempre son tan trabajadores? Porque quieren hacer una represa digna de aplauso",
"¿Por qué los murciélagos siempre son malos en matemáticas? Porque siempre confunden el número de alas",
"¿Por qué los pingüinos nunca se ponen tristes? Porque siempre tienen un amigo para abrazar",
"¿Por qué las abejas nunca van a la iglesia? Porque siempre tienen sus propias celdas para rezar",
"¿Por qué los hipopótamos nunca pueden ser buenos maestros? Porque siempre tienen un problema para subir a la pizarra",
"¿Por qué los leones nunca hacen yoga? Porque no pueden manejar la postura del león",
"¿Por qué los zorros siempre son buenos en matemáticas? Porque tienen un cerebro astuto",
"¿Por qué los osos polares nunca van a la playa? Porque siempre están ocupados construyendo iglús",
"¿Por qué los búhos siempre son los mejores consejeros? Porque siempre tienen una sabiduría nocturna",
"¿Por qué los elefantes nunca se van de vacaciones? Porque siempre tienen que recordar su maleta",
"¿Por qué las serpientes nunca pueden tocar música? Porque siempre tienen problemas para presionar las teclas con su cola",
"¿Por qué las luciérnagas siempre son tan brillantes? Porque quieren iluminar el camino de sus amigos",
"¿Por qué los murciélagos siempre tienen problemas para mantenerse en forma? Porque siempre se cuelgan del gimnasio",
"¿Por qué los caracoles nunca hacen buenos chistes? Porque siempre tardan demasiado en llegar al punto",
"¿Por qué las cucarachas siempre sobreviven a todo? Porque tienen una resistencia invencible",
"¿Por qué los cisnes nunca pueden ser artistas? Porque siempre tienen un problema para mantenerse quietos",
"¿Por qué los canguros siempre son los mejores para esquivar obstáculos? Porque siempre tienen un salto extra",











 ]

function funcionchistes() {
 
    let random = Math.floor(Math.random() * 143)
            console.log(random)
    let chiste = (chistes[random])
    console.log(chiste)
    let ja = document.getElementById("containerc").innerHTML = chiste

    console.log (ja)
}

